"""empty message

Revision ID: 1543e0924e22
Revises: 80ced5e730bf
Create Date: 2022-03-28 21:29:59.647712

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1543e0924e22'
down_revision = '80ced5e730bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
