"""empty message

Revision ID: 49299c85f004
Revises: ddc5a87a4373
Create Date: 2022-03-28 21:37:49.236749

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '49299c85f004'
down_revision = 'ddc5a87a4373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
