"""empty message

Revision ID: 72e58acf3de6
Revises: ca6520ecbafc
Create Date: 2022-03-28 21:17:38.158867

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '72e58acf3de6'
down_revision = 'ca6520ecbafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
