"""empty message

Revision ID: 80ced5e730bf
Revises: 3d27fb45c59b
Create Date: 2022-03-28 21:29:10.386594

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '80ced5e730bf'
down_revision = '3d27fb45c59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
